### ISSUE TITLE
Breaks irregular pluralizations

### ISSUE THREAD

**Issue by ctaintor** [joshmh/globalize2#10]
I'm using Rails 2.3.3 and have an irregular pluralization for curriculum and globalize2 is inadvertantly messing up the pluralization.  In this example, I have a model named "TranslatedCurriculum" with table named "translated_curricula" and a model named "UntranslatedCurriculum" with a table named "untranslated_curricula".  The TranslatedCurriculum has model translations, the UntranslatedCurriculum does not.  If I boot up a console, I'll get the following:
    >> TranslatedCurriculum.table_name
    => "translated_curriculums"
    >> UntranslatedCurriculum.table_name
    => "untranslated_curricula"

Notice that the TranslatedCurriculum is wrong (this leads to no queries working...).  The reason for this problem is that the translates() method in globalize2 is causing 'table_name' to be called on the TranslatedCurriculum object, thereby causing the table_name to be set for all time, since base.rb eventually calls set_table_name, which is defined as
    def set_table_name(value = nil, &block)
      define_attr_method :table_name, value, &block
    end
Since the irregular inflections haven't been loaded at this point, the incorrect inflection is saved.

I was able to fix this by patching the translates() method to have the following at the bottom of the method:
    define_attr_method :table_name do
      reset_table_name
    end 
which will mean that the table_name will be set at a later point in time (hopefully when the inflections have been loaded).

If you're trying to reproduce this, my environment.rb had the following block:
    ActiveSupport::Inflector.inflections do |inflect|
       inflect.irregular 'curriculum', 'curricula'
    end

**Comment by hukl** [comment]
If you could try to provide a failing test that would be helpful to figure out if the bug still exists and how to fix it. A lot has changed since then.

**Comment by ctaintor** [comment]
I'm unable to reproduce it now -- not sure what changed.

**Comment by hukl** [comment]
okay, i'll close it for now ;)
