### ISSUE TITLE
belongs_to association and reflection

### ISSUE THREAD

**Issue by adie** [joshmh/globalize2#12]
I'm using Rails 2.3.4 and latest version of Globalize2.
Don't know how to describe the issue, so here are the facts.
In globalize2/lib/globalize/model/active_record.rb on line 16:
    belongs_to "#{klass.name.underscore.gsub('/', '_')}".intern
But SomeModelTranslation.reflect_on_all_associations returns []
If I add
    self.globalize_proxy.belongs_to "#{self.name.underscore.gsub('/', '_')}".intern
after line 27 in globalize2/lib/globalize/model/active_record/translated.rb, or simply envoke
    SomeModelTranslation.belongs_to :some_model
then association builds properly.

**Comment by hukl** [comment]
the implementation in that area changed. please try again and open another issue if its persisting
