### ISSUE TITLE
table prefix

### ISSUE THREAD

**Issue by batdevis** [joshmh/globalize2#13]
create_translation_table! doesn't work correctly when I set a table prefix in my environment.rb:
config.active_record.table_name_prefix= '_'

here's my solution:
in file lib/globalize/model/active_record.rb
change 

`self.connection.create_table(translation_table_name) do |t|`

with

`self.connection.create_table("#{table_name_prefix}#{translation_table_name}#{table_name_suffix}") do |t|`

bye

Devis_

**Comment by hukl** [comment]
apparently this is fixed. just tried it out.
