### ISSUE TITLE
Broken session with Globalize::Translation::Static

### ISSUE THREAD

**Issue by al6x** [joshmh/globalize2#14]
Globalize2 uses Globalize::Translation::Static instead of String. So, if you save such translated string in session (flash[:notice] = t :some_message) and then try to use this session in another Rails App without installed Globalize2 you'll got and Error.

And second, instead of "my message" it will be stored as "full_qualified_class_name, version, bla-bla my message". And this is also problem because session size is limited.

it will:

**Comment by kares** [comment]
are You really sure this is a Globalize bug ?
this is how Globalize works and if it's decided to translate strings that way it's perfectly fine (You have some translation info with the string - like if it's a fallback translation, the locale used etc). 

what are Your suggestions, use String and forgot about all the added value of Static ?
without any suggestions I guess it won't get accepted, as the 2 rails app over the same session reason seems pretty non-standart ...

If Your using a t helper method why don't U get rid of Static there if You don't need it and it stands in Your way :

<pre>
<code>
def t
  t = I18n.t ...
  t.respond_to?(:original) ? t.original : t
end
</code>
</pre>

**Comment by al6x** [comment]
Probably You are right.
I'm not insist it's a bug, just pointed it out, in my case it results in broken session.

It's not obvious, that translated strings will not be marshaled properly. Maybe it make sense to explicitly warn about it in readme.
