### ISSUE TITLE
with globalize2, combining associations and named_scopes is not possible

### ISSUE THREAD

**Issue by tomash** [joshmh/globalize2#23]
To make it simple and quick: if a model has attributes translated using globalize2, belongs_to :someclass and has a named_scope, the three don't play nice, throwing
    ArgumentError: wrong number of arguments (2 for 1)
    from /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_collection.rb:340:in `respond_to?'

So, for instance if we have

```
class Category
  has_many :products
end

class Product
  belongs_to :category
  translates :title, :description
  named_scope :available, :conditions => {:available => true}
end
```

And then:
    c = Category.first
    c.products # works flawlessly
    c.products.available # throws wrong number of arguments

Commenting out translates clause of course fixes the issue, but I want my models to work using globalize2 ;)

**Comment by svenfuchs** [comment]
Hey Tomash! Now, that sounds like a serious problem. Are you using current master?

**Comment by tomash** [comment]
Yes I do, double-checked it and reinstalled (git submodules somehow don't work for me as expected). 

Were you able to reproduce it?

I'd hack a bit myself, but globalize2 uses quite a lot of ruby metaprogramming magic I don't feel comfortable enough yet.

**Comment by svenfuchs** [comment]
Ok thanks. 

No, I'm in the middle of something else right now. I'll ask a collaborator and look into it asap otherwise.

**Comment by hukl** [comment]
Hrm yep doesn't look good. Will investigate.

**Comment by hukl** [comment]
Fixed in http://github.com/joshmh/globalize2/commit/7672e7e001f3d3bc0c558b53392f37dd148ef974

**Comment by tomash** [comment]
Awesome! Thanks! :)
