### ISSUE TITLE
Find_by_xxx and updating xxx column doesn't work

### ISSUE THREAD

**Issue by josv** [joshmh/globalize2#27]
I found this bug report on the rails-i18n newsgroup:
http://www.mail-archive.com/rails-i18n@googlegroups.com/msg00990.html

I have the same problem and the solution which is suggested by the author seems to work:

add :readonly => false in the find method call
http://github.com/joshmh/globalize2/blob/master/lib/globalize/active_record.rb#L127

However I am not sure if this will break something else.

What is your opinion about this?

Thanks

John

**Comment by cs3b** [comment]
have the same problem, use the same sollutions - i don't think that this would break anything - rails by default make record as read only when you loading data by joins

**Comment by hukl** [comment]
Records retrieved by find_by_xx now have writable attributes. closed by f802f1927704556f4c802d65fcd5eed87aa97609
