### ISSUE TITLE
Create a migration script for Globalize1 / Rails 2.1 users

### ISSUE THREAD

**Issue by tomash** [joshmh/globalize2#3]
At the moment installing Globalize2 pretty much cripples an application with Globalize1 db and cannot be easily migrated (relevant fields/columns are not accessible).

A migration script (rake task?) that'd seamlessly transfer existing Globalize1 translations (minus the default records) to a Globalize2 translations -- would be great.

**Comment by tomash** [comment]
I've hacked a migration script that pretty much works for me considering model-translations migration from Globalize1 to Globalize2

http://gist.github.com/120867

**Comment by svenfuchs** [comment]
Nice! I've added this to the readme.

Thanks :)
