### ISSUE TITLE
How to delete a translation?

### ISSUE THREAD

**Issue by phlegx** [joshmh/globalize2#45]
How can I destroy a translation. It has work on the old version but not in the new version of globalize2. On the old version: If I did not have the "de" language in the params, then this language was deleted.

I use a batch translation: https://github.com/ZenCocoon/i18n_multi_locales_form

**Comment by phlegx** [comment]
Any ideas? I can found nothing on the Internet that can help me.

**Comment by lothar59** [comment]
same for me. If you destroy a record it doesn't work cause it says the field doesn't exist. create works fine but not destroy_all method.

I will need to delete in both tables. :/

Any help will be much appreciated.
