### ISSUE TITLE
Using create_translation_table on a working application

### ISSUE THREAD

**Issue by mrsimo** [joshmh/globalize2#5]
Would be nice to have something to get better migrations when you already have some elements of a model you want to add globalize2 support.

The table is created, but the current entries won't show anything on the translated fields. Also, the original field isn't destroyed, which might create problems.

What we do is iterate through the current elements creating entries on all the locales, and then destroy the original attribute.

**Comment by svenfuchs** [comment]
Sounds reasonable. Maybe you could provide a patch?
