### ISSUE TITLE
:text does not working

### ISSUE THREAD

**Issue by alec-c4** [joshmh/globalize2#7]
Hi,
i have migration with Post.create_translation_table! :title => :string, :body => :text
and model with translates :title, :body
and body is returning nil on read access (but writes ok). Whats wrong?

**Comment by hukl** [comment]
Hrm, that sounds weird. Are you using the most recent version? which database are you using and which adapter? Which version of Rails?

Kind regards , John

**Comment by alec-c4** [comment]
sqlite3 and rails 2.3.2. of course - latest version of globalize2

**Comment by hukl** [comment]
i'll try it out as soon as i can and look into it

**Comment by alec-c4** [comment]
thx

**Comment by hukl** [comment]
just tried it with a very basic demo app, created a model Post with exactly the same arguments and it works just fine. I'm using ruby, rails and sqlite3 from macports though. could you send me a sample app that doesn't work for you? email: contact (at) smyck (dot) org

**Comment by alec-c4** [comment]
hi, 
i've created new app from beginning - it works fine, possible there are problem somewhere in my code.

**Comment by alec-c4** [comment]
ooh, i've found where trouble is - there are conflict with acts_as_textiled. :(
