### ISSUE TITLE
create_translation_table! helper ignores config.active_record.table_name_prefix

### ISSUE THREAD

**Issue by ironoxid** [joshmh/globalize2#8]
Rails::Initializer.run do |config|
  ...
  config.active_record.table_name_prefix = 'myprefix_'
  ...
end

Rails migrations work well.

Ex. rails migration for model Page creates myprefix_pages. 

Globalize2 helper ignores table_name_prefix and creates page_translations (needed: myprefix_page_translations)

That miss cause this error:
Mysql::Error: Table 'my_db.myprefix_page_translations' doesn't exist: SELECT \* FROM `myprefix_page_translations` WHERE (`myprefix_page_translations`.page_id = 27 AND (`myprefix_page_translations`.`locale` IN ('en','root'))) 

ty

**Comment by hukl** [comment]
alright - I'll see how this can be fixed - shouldn't be too hard - if you have a patch yourself don't hesitate to send a pull request! I'm quite busy today. Kind regards

**Comment by ironoxid** [comment]
/lib/globalize/model/active_record/translated.rb:93
replace
translation_table_name = self.name.underscore + '_translations'
with
translation_table_name = self.table_name.singularize + '_translations'

**Comment by ironoxid** [comment]
after that patch globalize2 creates right tables, but there is a problem with bind columns for ex. model User - prefix_user_translations.user_id is expected but prefix_user_translations.prefix_user_id is created. I try to resolve and test this as soon as possible

**Comment by hukl** [comment]
is it just the helper that misbehaves or globalize2 entirely ? Whats it like when you manually create the translations table without the helper?

**Comment by hukl** [comment]
Can you check if that works for you ? Seems to work here

http://gist.github.com/160599

**Comment by ironoxid** [comment]
yes it seems to work very well. We have to update also drop_translation_table! at row 109 and 111 to rollback correctly. ty
