### ISSUE TITLE
makes sure interpolation does not break even with False as string

### ISSUE THREAD

**Issue by kares** [joshmh/globalize2#9]
there's a test with this issue's "title" name however it's not testing what it should be. 

it seems that the current implementation of the static backend is not compatible with the default simple backend in cases where the I18n.translate should return a true or false value, I have fixed the backend and added these tests :

http://gist.github.com/161328

the static backend fix and the tests are available in my globalize2 fork :

http://github.com/kares/globalize2/tree/master

**Comment by hukl** [comment]
The static backend was removed and it is recommended to use the i18m instead.

**Comment by kares** [comment]
ok then, thanx for the update.
